// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDELlh4hPRB8RbNF3DjcjO-c0x6gcgz2G4',
    appId: '1:92657049924:web:d3a25e26fe14a6795ef711',
    messagingSenderId: '92657049924',
    projectId: 'chatapp-e29cc',
    authDomain: 'chatapp-e29cc.firebaseapp.com',
    storageBucket: 'chatapp-e29cc.appspot.com',
    measurementId: 'G-KKNBSQJZ46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADGtYY8AuJdzMVBn3o-ZCu_TQvxW2BLa0',
    appId: '1:92657049924:android:5c3bd43a239a924b5ef711',
    messagingSenderId: '92657049924',
    projectId: 'chatapp-e29cc',
    storageBucket: 'chatapp-e29cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWyBm-j6fPoG7QptJd5ynOxEcY-PRuGA0',
    appId: '1:92657049924:ios:fc96e981739e45255ef711',
    messagingSenderId: '92657049924',
    projectId: 'chatapp-e29cc',
    storageBucket: 'chatapp-e29cc.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWyBm-j6fPoG7QptJd5ynOxEcY-PRuGA0',
    appId: '1:92657049924:ios:fc96e981739e45255ef711',
    messagingSenderId: '92657049924',
    projectId: 'chatapp-e29cc',
    storageBucket: 'chatapp-e29cc.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDELlh4hPRB8RbNF3DjcjO-c0x6gcgz2G4',
    appId: '1:92657049924:web:ed09a8b669ed3b965ef711',
    messagingSenderId: '92657049924',
    projectId: 'chatapp-e29cc',
    authDomain: 'chatapp-e29cc.firebaseapp.com',
    storageBucket: 'chatapp-e29cc.appspot.com',
    measurementId: 'G-EYNH21K86Z',
  );
}
